
package org.jboss.samples.webservices.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2.6-patch-01
 * Mon Jul 18 14:37:36 CDT 2011
 * Generated source version: 2.2.6-patch-01
 */

@XmlRootElement(name = "validateClaim", namespace = "http://webservices.samples.jboss.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "validateClaim", namespace = "http://webservices.samples.jboss.org/")

public class ValidateClaim {

    @XmlElement(name = "arg0")
    private org.jboss.samples.domain.Claim arg0;

    public org.jboss.samples.domain.Claim getArg0() {
        return this.arg0;
    }

    public void setArg0(org.jboss.samples.domain.Claim newArg0)  {
        this.arg0 = newArg0;
    }

}

